### ISSUE TITLE
git stuff

### ISSUE THREAD

**Issue by nobe4** [nobe4/dotfiles#35]
From https://www.youtube.com/watch?v=aolI_Rz0ZqY 

```[tasklist]
### Tasks
- [ ] git log -L
- [ ] git log -L :FunctionName:path/to/file
- [ ] git log -S 'regexp' -p
- [ ] git reflog
- [x] git diff --word-diff
- [ ] git blame -L
- [ ] git blame -w -C
- [x] git config includeif
- [x] git config rerere.enable
- [x] branch descriptions
- [x] https://gist.github.com/schacon/e9e743dee2e92db9a464619b99e94eff
- [x] git branch --column
- [x] git config column.ui auto
- [x] git config branch.sort ...
- [x] git columns
- [x] git push --force-with-lease
- [x] git maintenance => seems to work only on a repo-basis, and the repo name is included in the global gitconfig, 🤔
- [x] git maintenance start in all repos      run this from projector     have an alias to do that for all repos
- [ ] config fetch.writeCommitGraph
- [ ] config core.fsmonitor
- [ ] config core.untrackedcache
- [ ] git clone --filter=blob:none
- [ ] git clone --filter=tree:0
- [x] vim fugitive difftastic
```
